baseURL = "https://brit-hugo.mansoorbarri.com" 
languageCode = "en-gb"
theme = "brit-hugo"

[Params]
    title = "Brit Hugo"
    subtitle = "Inspired by Brittany Chiang"
    description = "I build pixel-perfect, engaging,<br> and accessible digital experience."
    favicon = "https://brittanychiang.com/favicon/android-chrome-512x512.png"
    about = '''
        Back in 2012, I decided to try my hand at creating custom Tumblr
        themes and tumbled head first into the rabbit hole of coding and
        web development. Fast-forward to today, and I’ve had the
        privilege of building software for an
        <a href="">advertising agency</a>, a <a href="">start-up</a>, a
        <a href="">student-led design studio</a>, and a
        <a href="">huge corporation</a>.
        <br><br>
        My main focus these days is building products and leading
        projects for our clients at <a href="">Upstatement</a>. I most
        enjoy building software in the sweet spot where design and
        engineering meet — things that look good but are also built well
        under the hood. In my free time, I've also released an
        <a href="">online video course</a> that covers everything you
        need to know to build a web app with the Spotify API.
        <br><br>
        When I’m not at the computer, I’m usually rock climbing,
        reading, hanging out with my wife and two cats, or running
        around Hyrule searching for <a href="">Korok seeds</a>.
    '''
    footer = "2024 All Rights Reserved | Made using <a href='gohugo.io'>Hugo</a>"


socials = [     
    {name = "twitter", username = "test"},    
    {name = "facebook", username = "test"},    
    {name = "github", username = "test"},    
    {name = "instagram", username = "test"},    
    {name = "tiktok", username = "test"},    
]
